//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresim
    {
        public int adres_id { get; set; }
        public string adres_telefon { get; set; }
        public string adres_gmail { get; set; }
        public string adres_facebook { get; set; }
        public string adres_instagram { get; set; }
        public string adres_youtube { get; set; }
        public string adres_about_text { get; set; }
    }
}
