//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elaqe
    {
        public int elaqe_id { get; set; }
        public string elaqe_ad { get; set; }
        public string elaqe_soyad { get; set; }
        public string elaqe_telefon { get; set; }
        public string elaqe_mesaji { get; set; }
    }
}
