//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endirim
    {
        public int endirim_id { get; set; }
        public string endirim_novu { get; set; }
        public string edirim_faiz { get; set; }
        public string endirim_detail { get; set; }
    }
}
