//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galereya
    {
        public int galery_id { get; set; }
        public string galery_header { get; set; }
        public string galery_text { get; set; }
        public string galery_image { get; set; }
    }
}
