//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public int kampanya_id { get; set; }
        public string kampanya_adi { get; set; }
        public string kampanya_mehsullari { get; set; }
        public string kampanya_qiymeti { get; set; }
        public string kampanya_info { get; set; }
        public string kampanya_photo { get; set; }
        public string kampanya_link { get; set; }
    }
}
