//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Mallar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mallar()
        {
            this.Karusels = new HashSet<Karusel>();
            this.Slayders = new HashSet<Slayder>();
        }
    
        public int mal_id { get; set; }
        public string mal_adi { get; set; }
        public string mal_qiymeti { get; set; }
        public string mal_youtube_link { get; set; }
        [UIHint("tinymce_jquery_full"), AllowHtml]
        public string mal_web_link { get; set; }
        [UIHint("tinymce_jquery_full"), AllowHtml]
        public string mal_info { get; set; }
        public string mal_bawliq { get; set; }
        public Nullable<int> mal_kateqoriyasi { get; set; }
        public string mal_resmi { get; set; }
        public Nullable<int> mal_novu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karusel> Karusels { get; set; }
        public virtual Kategoriya Kategoriya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slayder> Slayders { get; set; }
        public virtual MalNovu MalNovu { get; set; }
    }
}
