//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servi
    {
        public int servis_id { get; set; }
        public string servis_adi { get; set; }
        public string servis_content { get; set; }
        public string servis_icon { get; set; }
    }
}
