//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaznovu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaznovu()
        {
            this.Zakazims = new HashSet<Zakazim>();
        }
    
        public int zakaznovu_id { get; set; }
        public string zakaznovu_ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazim> Zakazims { get; set; }
    }
}
