//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzmanAzWebPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazim
    {
        public int zakazim_id { get; set; }
        public string zakazim_adi_soyad { get; set; }
        public string zakazim_telefon { get; set; }
        public string zakazim_mehsul { get; set; }
        public Nullable<System.DateTime> zakaz_vaxti { get; set; }
        public Nullable<int> zakaz_novu_id { get; set; }
    
        public virtual Zakaznovu Zakaznovu { get; set; }
    }
}
